// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Organ is the predicate function for organ builders.
type Organ func(*sql.Selector)

// Physician is the predicate function for physician builders.
type Physician func(*sql.Selector)

// Spaciality is the predicate function for spaciality builders.
type Spaciality func(*sql.Selector)

// TypeDisease is the predicate function for typedisease builders.
type TypeDisease func(*sql.Selector)
