// Code generated by entc, DO NOT EDIT.

package typedisease

const (
	// Label holds the string label denoting the typedisease type in the database.
	Label = "type_disease"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDiseaseName holds the string denoting the diseasename field in the database.
	FieldDiseaseName = "disease_name"

	// EdgeFortype holds the string denoting the fortype edge name in mutations.
	EdgeFortype = "fortype"

	// Table holds the table name of the typedisease in the database.
	Table = "type_diseases"
	// FortypeTable is the table the holds the fortype relation/edge.
	FortypeTable = "spacialities"
	// FortypeInverseTable is the table name for the Spaciality entity.
	// It exists in this package in order to avoid circular dependency with the "spaciality" package.
	FortypeInverseTable = "spacialities"
	// FortypeColumn is the table column denoting the fortype relation/edge.
	FortypeColumn = "type_disease_fortype"
)

// Columns holds all SQL columns for typedisease fields.
var Columns = []string{
	FieldID,
	FieldDiseaseName,
}

var (
	// DiseaseNameValidator is a validator for the "DiseaseName" field. It is called by the builders before save.
	DiseaseNameValidator func(string) error
)
