// Code generated by entc, DO NOT EDIT.

package spaciality

const (
	// Label holds the string label denoting the spaciality type in the database.
	Label = "spaciality"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"

	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeOgan holds the string denoting the ogan edge name in mutations.
	EdgeOgan = "ogan"
	// EdgeType holds the string denoting the type edge name in mutations.
	EdgeType = "type"

	// Table holds the table name of the spaciality in the database.
	Table = "spacialities"
	// UserTable is the table the holds the user relation/edge.
	UserTable = "spacialities"
	// UserInverseTable is the table name for the Physician entity.
	// It exists in this package in order to avoid circular dependency with the "physician" package.
	UserInverseTable = "physicians"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "physician_foruser"
	// OganTable is the table the holds the ogan relation/edge.
	OganTable = "spacialities"
	// OganInverseTable is the table name for the Organ entity.
	// It exists in this package in order to avoid circular dependency with the "organ" package.
	OganInverseTable = "organs"
	// OganColumn is the table column denoting the ogan relation/edge.
	OganColumn = "organ_forogan"
	// TypeTable is the table the holds the type relation/edge.
	TypeTable = "spacialities"
	// TypeInverseTable is the table name for the TypeDisease entity.
	// It exists in this package in order to avoid circular dependency with the "typedisease" package.
	TypeInverseTable = "type_diseases"
	// TypeColumn is the table column denoting the type relation/edge.
	TypeColumn = "type_disease_fortype"
)

// Columns holds all SQL columns for spaciality fields.
var Columns = []string{
	FieldID,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Spaciality type.
var ForeignKeys = []string{
	"organ_forogan",
	"physician_foruser",
	"type_disease_fortype",
}
