// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/Pichais/app/ent/organ"
	"github.com/Pichais/app/ent/spaciality"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// OrganCreate is the builder for creating a Organ entity.
type OrganCreate struct {
	config
	mutation *OrganMutation
	hooks    []Hook
}

// SetOrganName sets the OrganName field.
func (oc *OrganCreate) SetOrganName(s string) *OrganCreate {
	oc.mutation.SetOrganName(s)
	return oc
}

// AddForoganIDs adds the forogan edge to Spaciality by ids.
func (oc *OrganCreate) AddForoganIDs(ids ...int) *OrganCreate {
	oc.mutation.AddForoganIDs(ids...)
	return oc
}

// AddForogan adds the forogan edges to Spaciality.
func (oc *OrganCreate) AddForogan(s ...*Spaciality) *OrganCreate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return oc.AddForoganIDs(ids...)
}

// Mutation returns the OrganMutation object of the builder.
func (oc *OrganCreate) Mutation() *OrganMutation {
	return oc.mutation
}

// Save creates the Organ in the database.
func (oc *OrganCreate) Save(ctx context.Context) (*Organ, error) {
	if _, ok := oc.mutation.OrganName(); !ok {
		return nil, &ValidationError{Name: "OrganName", err: errors.New("ent: missing required field \"OrganName\"")}
	}
	if v, ok := oc.mutation.OrganName(); ok {
		if err := organ.OrganNameValidator(v); err != nil {
			return nil, &ValidationError{Name: "OrganName", err: fmt.Errorf("ent: validator failed for field \"OrganName\": %w", err)}
		}
	}
	var (
		err  error
		node *Organ
	)
	if len(oc.hooks) == 0 {
		node, err = oc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*OrganMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			oc.mutation = mutation
			node, err = oc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(oc.hooks) - 1; i >= 0; i-- {
			mut = oc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, oc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (oc *OrganCreate) SaveX(ctx context.Context) *Organ {
	v, err := oc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (oc *OrganCreate) sqlSave(ctx context.Context) (*Organ, error) {
	o, _spec := oc.createSpec()
	if err := sqlgraph.CreateNode(ctx, oc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	o.ID = int(id)
	return o, nil
}

func (oc *OrganCreate) createSpec() (*Organ, *sqlgraph.CreateSpec) {
	var (
		o     = &Organ{config: oc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: organ.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: organ.FieldID,
			},
		}
	)
	if value, ok := oc.mutation.OrganName(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: organ.FieldOrganName,
		})
		o.OrganName = value
	}
	if nodes := oc.mutation.ForoganIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   organ.ForoganTable,
			Columns: []string{organ.ForoganColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: spaciality.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return o, _spec
}
