// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/Pichais/app/ent/physician"
	"github.com/Pichais/app/ent/spaciality"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// PhysicianCreate is the builder for creating a Physician entity.
type PhysicianCreate struct {
	config
	mutation *PhysicianMutation
	hooks    []Hook
}

// SetPhysicianName sets the PhysicianName field.
func (pc *PhysicianCreate) SetPhysicianName(s string) *PhysicianCreate {
	pc.mutation.SetPhysicianName(s)
	return pc
}

// SetPhysicianEmail sets the PhysicianEmail field.
func (pc *PhysicianCreate) SetPhysicianEmail(s string) *PhysicianCreate {
	pc.mutation.SetPhysicianEmail(s)
	return pc
}

// AddForuserIDs adds the foruser edge to Spaciality by ids.
func (pc *PhysicianCreate) AddForuserIDs(ids ...int) *PhysicianCreate {
	pc.mutation.AddForuserIDs(ids...)
	return pc
}

// AddForuser adds the foruser edges to Spaciality.
func (pc *PhysicianCreate) AddForuser(s ...*Spaciality) *PhysicianCreate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return pc.AddForuserIDs(ids...)
}

// Mutation returns the PhysicianMutation object of the builder.
func (pc *PhysicianCreate) Mutation() *PhysicianMutation {
	return pc.mutation
}

// Save creates the Physician in the database.
func (pc *PhysicianCreate) Save(ctx context.Context) (*Physician, error) {
	if _, ok := pc.mutation.PhysicianName(); !ok {
		return nil, &ValidationError{Name: "PhysicianName", err: errors.New("ent: missing required field \"PhysicianName\"")}
	}
	if v, ok := pc.mutation.PhysicianName(); ok {
		if err := physician.PhysicianNameValidator(v); err != nil {
			return nil, &ValidationError{Name: "PhysicianName", err: fmt.Errorf("ent: validator failed for field \"PhysicianName\": %w", err)}
		}
	}
	if _, ok := pc.mutation.PhysicianEmail(); !ok {
		return nil, &ValidationError{Name: "PhysicianEmail", err: errors.New("ent: missing required field \"PhysicianEmail\"")}
	}
	if v, ok := pc.mutation.PhysicianEmail(); ok {
		if err := physician.PhysicianEmailValidator(v); err != nil {
			return nil, &ValidationError{Name: "PhysicianEmail", err: fmt.Errorf("ent: validator failed for field \"PhysicianEmail\": %w", err)}
		}
	}
	var (
		err  error
		node *Physician
	)
	if len(pc.hooks) == 0 {
		node, err = pc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PhysicianMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pc.mutation = mutation
			node, err = pc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(pc.hooks) - 1; i >= 0; i-- {
			mut = pc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (pc *PhysicianCreate) SaveX(ctx context.Context) *Physician {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (pc *PhysicianCreate) sqlSave(ctx context.Context) (*Physician, error) {
	ph, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	ph.ID = int(id)
	return ph, nil
}

func (pc *PhysicianCreate) createSpec() (*Physician, *sqlgraph.CreateSpec) {
	var (
		ph    = &Physician{config: pc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: physician.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: physician.FieldID,
			},
		}
	)
	if value, ok := pc.mutation.PhysicianName(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: physician.FieldPhysicianName,
		})
		ph.PhysicianName = value
	}
	if value, ok := pc.mutation.PhysicianEmail(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: physician.FieldPhysicianEmail,
		})
		ph.PhysicianEmail = value
	}
	if nodes := pc.mutation.ForuserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   physician.ForuserTable,
			Columns: []string{physician.ForuserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: spaciality.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return ph, _spec
}
