// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/Pichais/app/ent/physician"
	"github.com/Pichais/app/ent/predicate"
	"github.com/Pichais/app/ent/spaciality"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// PhysicianUpdate is the builder for updating Physician entities.
type PhysicianUpdate struct {
	config
	hooks      []Hook
	mutation   *PhysicianMutation
	predicates []predicate.Physician
}

// Where adds a new predicate for the builder.
func (pu *PhysicianUpdate) Where(ps ...predicate.Physician) *PhysicianUpdate {
	pu.predicates = append(pu.predicates, ps...)
	return pu
}

// SetPhysicianName sets the PhysicianName field.
func (pu *PhysicianUpdate) SetPhysicianName(s string) *PhysicianUpdate {
	pu.mutation.SetPhysicianName(s)
	return pu
}

// SetPhysicianEmail sets the PhysicianEmail field.
func (pu *PhysicianUpdate) SetPhysicianEmail(s string) *PhysicianUpdate {
	pu.mutation.SetPhysicianEmail(s)
	return pu
}

// AddForuserIDs adds the foruser edge to Spaciality by ids.
func (pu *PhysicianUpdate) AddForuserIDs(ids ...int) *PhysicianUpdate {
	pu.mutation.AddForuserIDs(ids...)
	return pu
}

// AddForuser adds the foruser edges to Spaciality.
func (pu *PhysicianUpdate) AddForuser(s ...*Spaciality) *PhysicianUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return pu.AddForuserIDs(ids...)
}

// Mutation returns the PhysicianMutation object of the builder.
func (pu *PhysicianUpdate) Mutation() *PhysicianMutation {
	return pu.mutation
}

// RemoveForuserIDs removes the foruser edge to Spaciality by ids.
func (pu *PhysicianUpdate) RemoveForuserIDs(ids ...int) *PhysicianUpdate {
	pu.mutation.RemoveForuserIDs(ids...)
	return pu
}

// RemoveForuser removes foruser edges to Spaciality.
func (pu *PhysicianUpdate) RemoveForuser(s ...*Spaciality) *PhysicianUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return pu.RemoveForuserIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (pu *PhysicianUpdate) Save(ctx context.Context) (int, error) {
	if v, ok := pu.mutation.PhysicianName(); ok {
		if err := physician.PhysicianNameValidator(v); err != nil {
			return 0, &ValidationError{Name: "PhysicianName", err: fmt.Errorf("ent: validator failed for field \"PhysicianName\": %w", err)}
		}
	}
	if v, ok := pu.mutation.PhysicianEmail(); ok {
		if err := physician.PhysicianEmailValidator(v); err != nil {
			return 0, &ValidationError{Name: "PhysicianEmail", err: fmt.Errorf("ent: validator failed for field \"PhysicianEmail\": %w", err)}
		}
	}

	var (
		err      error
		affected int
	)
	if len(pu.hooks) == 0 {
		affected, err = pu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PhysicianMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pu.mutation = mutation
			affected, err = pu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(pu.hooks) - 1; i >= 0; i-- {
			mut = pu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (pu *PhysicianUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *PhysicianUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *PhysicianUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (pu *PhysicianUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   physician.Table,
			Columns: physician.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: physician.FieldID,
			},
		},
	}
	if ps := pu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.PhysicianName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: physician.FieldPhysicianName,
		})
	}
	if value, ok := pu.mutation.PhysicianEmail(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: physician.FieldPhysicianEmail,
		})
	}
	if nodes := pu.mutation.RemovedForuserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   physician.ForuserTable,
			Columns: []string{physician.ForuserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: spaciality.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.ForuserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   physician.ForuserTable,
			Columns: []string{physician.ForuserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: spaciality.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{physician.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// PhysicianUpdateOne is the builder for updating a single Physician entity.
type PhysicianUpdateOne struct {
	config
	hooks    []Hook
	mutation *PhysicianMutation
}

// SetPhysicianName sets the PhysicianName field.
func (puo *PhysicianUpdateOne) SetPhysicianName(s string) *PhysicianUpdateOne {
	puo.mutation.SetPhysicianName(s)
	return puo
}

// SetPhysicianEmail sets the PhysicianEmail field.
func (puo *PhysicianUpdateOne) SetPhysicianEmail(s string) *PhysicianUpdateOne {
	puo.mutation.SetPhysicianEmail(s)
	return puo
}

// AddForuserIDs adds the foruser edge to Spaciality by ids.
func (puo *PhysicianUpdateOne) AddForuserIDs(ids ...int) *PhysicianUpdateOne {
	puo.mutation.AddForuserIDs(ids...)
	return puo
}

// AddForuser adds the foruser edges to Spaciality.
func (puo *PhysicianUpdateOne) AddForuser(s ...*Spaciality) *PhysicianUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return puo.AddForuserIDs(ids...)
}

// Mutation returns the PhysicianMutation object of the builder.
func (puo *PhysicianUpdateOne) Mutation() *PhysicianMutation {
	return puo.mutation
}

// RemoveForuserIDs removes the foruser edge to Spaciality by ids.
func (puo *PhysicianUpdateOne) RemoveForuserIDs(ids ...int) *PhysicianUpdateOne {
	puo.mutation.RemoveForuserIDs(ids...)
	return puo
}

// RemoveForuser removes foruser edges to Spaciality.
func (puo *PhysicianUpdateOne) RemoveForuser(s ...*Spaciality) *PhysicianUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return puo.RemoveForuserIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (puo *PhysicianUpdateOne) Save(ctx context.Context) (*Physician, error) {
	if v, ok := puo.mutation.PhysicianName(); ok {
		if err := physician.PhysicianNameValidator(v); err != nil {
			return nil, &ValidationError{Name: "PhysicianName", err: fmt.Errorf("ent: validator failed for field \"PhysicianName\": %w", err)}
		}
	}
	if v, ok := puo.mutation.PhysicianEmail(); ok {
		if err := physician.PhysicianEmailValidator(v); err != nil {
			return nil, &ValidationError{Name: "PhysicianEmail", err: fmt.Errorf("ent: validator failed for field \"PhysicianEmail\": %w", err)}
		}
	}

	var (
		err  error
		node *Physician
	)
	if len(puo.hooks) == 0 {
		node, err = puo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PhysicianMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			puo.mutation = mutation
			node, err = puo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(puo.hooks) - 1; i >= 0; i-- {
			mut = puo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, puo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (puo *PhysicianUpdateOne) SaveX(ctx context.Context) *Physician {
	ph, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return ph
}

// Exec executes the query on the entity.
func (puo *PhysicianUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *PhysicianUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (puo *PhysicianUpdateOne) sqlSave(ctx context.Context) (ph *Physician, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   physician.Table,
			Columns: physician.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: physician.FieldID,
			},
		},
	}
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Physician.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := puo.mutation.PhysicianName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: physician.FieldPhysicianName,
		})
	}
	if value, ok := puo.mutation.PhysicianEmail(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: physician.FieldPhysicianEmail,
		})
	}
	if nodes := puo.mutation.RemovedForuserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   physician.ForuserTable,
			Columns: []string{physician.ForuserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: spaciality.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.ForuserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   physician.ForuserTable,
			Columns: []string{physician.ForuserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: spaciality.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	ph = &Physician{config: puo.config}
	_spec.Assign = ph.assignValues
	_spec.ScanValues = ph.scanValues()
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{physician.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return ph, nil
}
