// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/Pichais/app/ent/predicate"
	"github.com/Pichais/app/ent/typedisease"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// TypeDiseaseDelete is the builder for deleting a TypeDisease entity.
type TypeDiseaseDelete struct {
	config
	hooks      []Hook
	mutation   *TypeDiseaseMutation
	predicates []predicate.TypeDisease
}

// Where adds a new predicate to the delete builder.
func (tdd *TypeDiseaseDelete) Where(ps ...predicate.TypeDisease) *TypeDiseaseDelete {
	tdd.predicates = append(tdd.predicates, ps...)
	return tdd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (tdd *TypeDiseaseDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(tdd.hooks) == 0 {
		affected, err = tdd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TypeDiseaseMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			tdd.mutation = mutation
			affected, err = tdd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(tdd.hooks) - 1; i >= 0; i-- {
			mut = tdd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tdd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (tdd *TypeDiseaseDelete) ExecX(ctx context.Context) int {
	n, err := tdd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (tdd *TypeDiseaseDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: typedisease.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: typedisease.FieldID,
			},
		},
	}
	if ps := tdd.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, tdd.driver, _spec)
}

// TypeDiseaseDeleteOne is the builder for deleting a single TypeDisease entity.
type TypeDiseaseDeleteOne struct {
	tdd *TypeDiseaseDelete
}

// Exec executes the deletion query.
func (tddo *TypeDiseaseDeleteOne) Exec(ctx context.Context) error {
	n, err := tddo.tdd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{typedisease.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tddo *TypeDiseaseDeleteOne) ExecX(ctx context.Context) {
	tddo.tdd.ExecX(ctx)
}
