// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"math"

	"github.com/Pichais/app/ent/predicate"
	"github.com/Pichais/app/ent/spaciality"
	"github.com/Pichais/app/ent/typedisease"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// TypeDiseaseQuery is the builder for querying TypeDisease entities.
type TypeDiseaseQuery struct {
	config
	limit      *int
	offset     *int
	order      []OrderFunc
	unique     []string
	predicates []predicate.TypeDisease
	// eager-loading edges.
	withFortype *SpacialityQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the builder.
func (tdq *TypeDiseaseQuery) Where(ps ...predicate.TypeDisease) *TypeDiseaseQuery {
	tdq.predicates = append(tdq.predicates, ps...)
	return tdq
}

// Limit adds a limit step to the query.
func (tdq *TypeDiseaseQuery) Limit(limit int) *TypeDiseaseQuery {
	tdq.limit = &limit
	return tdq
}

// Offset adds an offset step to the query.
func (tdq *TypeDiseaseQuery) Offset(offset int) *TypeDiseaseQuery {
	tdq.offset = &offset
	return tdq
}

// Order adds an order step to the query.
func (tdq *TypeDiseaseQuery) Order(o ...OrderFunc) *TypeDiseaseQuery {
	tdq.order = append(tdq.order, o...)
	return tdq
}

// QueryFortype chains the current query on the fortype edge.
func (tdq *TypeDiseaseQuery) QueryFortype() *SpacialityQuery {
	query := &SpacialityQuery{config: tdq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tdq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(typedisease.Table, typedisease.FieldID, tdq.sqlQuery()),
			sqlgraph.To(spaciality.Table, spaciality.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, typedisease.FortypeTable, typedisease.FortypeColumn),
		)
		fromU = sqlgraph.SetNeighbors(tdq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first TypeDisease entity in the query. Returns *NotFoundError when no typedisease was found.
func (tdq *TypeDiseaseQuery) First(ctx context.Context) (*TypeDisease, error) {
	tds, err := tdq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(tds) == 0 {
		return nil, &NotFoundError{typedisease.Label}
	}
	return tds[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tdq *TypeDiseaseQuery) FirstX(ctx context.Context) *TypeDisease {
	td, err := tdq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return td
}

// FirstID returns the first TypeDisease id in the query. Returns *NotFoundError when no id was found.
func (tdq *TypeDiseaseQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tdq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{typedisease.Label}
		return
	}
	return ids[0], nil
}

// FirstXID is like FirstID, but panics if an error occurs.
func (tdq *TypeDiseaseQuery) FirstXID(ctx context.Context) int {
	id, err := tdq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns the only TypeDisease entity in the query, returns an error if not exactly one entity was returned.
func (tdq *TypeDiseaseQuery) Only(ctx context.Context) (*TypeDisease, error) {
	tds, err := tdq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(tds) {
	case 1:
		return tds[0], nil
	case 0:
		return nil, &NotFoundError{typedisease.Label}
	default:
		return nil, &NotSingularError{typedisease.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tdq *TypeDiseaseQuery) OnlyX(ctx context.Context) *TypeDisease {
	td, err := tdq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return td
}

// OnlyID returns the only TypeDisease id in the query, returns an error if not exactly one id was returned.
func (tdq *TypeDiseaseQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tdq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{typedisease.Label}
	default:
		err = &NotSingularError{typedisease.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tdq *TypeDiseaseQuery) OnlyIDX(ctx context.Context) int {
	id, err := tdq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TypeDiseases.
func (tdq *TypeDiseaseQuery) All(ctx context.Context) ([]*TypeDisease, error) {
	if err := tdq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return tdq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (tdq *TypeDiseaseQuery) AllX(ctx context.Context) []*TypeDisease {
	tds, err := tdq.All(ctx)
	if err != nil {
		panic(err)
	}
	return tds
}

// IDs executes the query and returns a list of TypeDisease ids.
func (tdq *TypeDiseaseQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := tdq.Select(typedisease.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tdq *TypeDiseaseQuery) IDsX(ctx context.Context) []int {
	ids, err := tdq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tdq *TypeDiseaseQuery) Count(ctx context.Context) (int, error) {
	if err := tdq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return tdq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (tdq *TypeDiseaseQuery) CountX(ctx context.Context) int {
	count, err := tdq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tdq *TypeDiseaseQuery) Exist(ctx context.Context) (bool, error) {
	if err := tdq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return tdq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (tdq *TypeDiseaseQuery) ExistX(ctx context.Context) bool {
	exist, err := tdq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the query builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tdq *TypeDiseaseQuery) Clone() *TypeDiseaseQuery {
	return &TypeDiseaseQuery{
		config:     tdq.config,
		limit:      tdq.limit,
		offset:     tdq.offset,
		order:      append([]OrderFunc{}, tdq.order...),
		unique:     append([]string{}, tdq.unique...),
		predicates: append([]predicate.TypeDisease{}, tdq.predicates...),
		// clone intermediate query.
		sql:  tdq.sql.Clone(),
		path: tdq.path,
	}
}

//  WithFortype tells the query-builder to eager-loads the nodes that are connected to
// the "fortype" edge. The optional arguments used to configure the query builder of the edge.
func (tdq *TypeDiseaseQuery) WithFortype(opts ...func(*SpacialityQuery)) *TypeDiseaseQuery {
	query := &SpacialityQuery{config: tdq.config}
	for _, opt := range opts {
		opt(query)
	}
	tdq.withFortype = query
	return tdq
}

// GroupBy used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		DiseaseName string `json:"DiseaseName,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TypeDisease.Query().
//		GroupBy(typedisease.FieldDiseaseName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (tdq *TypeDiseaseQuery) GroupBy(field string, fields ...string) *TypeDiseaseGroupBy {
	group := &TypeDiseaseGroupBy{config: tdq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := tdq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return tdq.sqlQuery(), nil
	}
	return group
}

// Select one or more fields from the given query.
//
// Example:
//
//	var v []struct {
//		DiseaseName string `json:"DiseaseName,omitempty"`
//	}
//
//	client.TypeDisease.Query().
//		Select(typedisease.FieldDiseaseName).
//		Scan(ctx, &v)
//
func (tdq *TypeDiseaseQuery) Select(field string, fields ...string) *TypeDiseaseSelect {
	selector := &TypeDiseaseSelect{config: tdq.config}
	selector.fields = append([]string{field}, fields...)
	selector.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := tdq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return tdq.sqlQuery(), nil
	}
	return selector
}

func (tdq *TypeDiseaseQuery) prepareQuery(ctx context.Context) error {
	if tdq.path != nil {
		prev, err := tdq.path(ctx)
		if err != nil {
			return err
		}
		tdq.sql = prev
	}
	return nil
}

func (tdq *TypeDiseaseQuery) sqlAll(ctx context.Context) ([]*TypeDisease, error) {
	var (
		nodes       = []*TypeDisease{}
		_spec       = tdq.querySpec()
		loadedTypes = [1]bool{
			tdq.withFortype != nil,
		}
	)
	_spec.ScanValues = func() []interface{} {
		node := &TypeDisease{config: tdq.config}
		nodes = append(nodes, node)
		values := node.scanValues()
		return values
	}
	_spec.Assign = func(values ...interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(values...)
	}
	if err := sqlgraph.QueryNodes(ctx, tdq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := tdq.withFortype; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		nodeids := make(map[int]*TypeDisease)
		for i := range nodes {
			fks = append(fks, nodes[i].ID)
			nodeids[nodes[i].ID] = nodes[i]
		}
		query.withFKs = true
		query.Where(predicate.Spaciality(func(s *sql.Selector) {
			s.Where(sql.InValues(typedisease.FortypeColumn, fks...))
		}))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			fk := n.type_disease_fortype
			if fk == nil {
				return nil, fmt.Errorf(`foreign-key "type_disease_fortype" is nil for node %v`, n.ID)
			}
			node, ok := nodeids[*fk]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "type_disease_fortype" returned %v for node %v`, *fk, n.ID)
			}
			node.Edges.Fortype = append(node.Edges.Fortype, n)
		}
	}

	return nodes, nil
}

func (tdq *TypeDiseaseQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tdq.querySpec()
	return sqlgraph.CountNodes(ctx, tdq.driver, _spec)
}

func (tdq *TypeDiseaseQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := tdq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %v", err)
	}
	return n > 0, nil
}

func (tdq *TypeDiseaseQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   typedisease.Table,
			Columns: typedisease.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: typedisease.FieldID,
			},
		},
		From:   tdq.sql,
		Unique: true,
	}
	if ps := tdq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tdq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tdq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tdq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tdq *TypeDiseaseQuery) sqlQuery() *sql.Selector {
	builder := sql.Dialect(tdq.driver.Dialect())
	t1 := builder.Table(typedisease.Table)
	selector := builder.Select(t1.Columns(typedisease.Columns...)...).From(t1)
	if tdq.sql != nil {
		selector = tdq.sql
		selector.Select(selector.Columns(typedisease.Columns...)...)
	}
	for _, p := range tdq.predicates {
		p(selector)
	}
	for _, p := range tdq.order {
		p(selector)
	}
	if offset := tdq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tdq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TypeDiseaseGroupBy is the builder for group-by TypeDisease entities.
type TypeDiseaseGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tdgb *TypeDiseaseGroupBy) Aggregate(fns ...AggregateFunc) *TypeDiseaseGroupBy {
	tdgb.fns = append(tdgb.fns, fns...)
	return tdgb
}

// Scan applies the group-by query and scan the result into the given value.
func (tdgb *TypeDiseaseGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := tdgb.path(ctx)
	if err != nil {
		return err
	}
	tdgb.sql = query
	return tdgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (tdgb *TypeDiseaseGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := tdgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by. It is only allowed when querying group-by with one field.
func (tdgb *TypeDiseaseGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(tdgb.fields) > 1 {
		return nil, errors.New("ent: TypeDiseaseGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := tdgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (tdgb *TypeDiseaseGroupBy) StringsX(ctx context.Context) []string {
	v, err := tdgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from group-by. It is only allowed when querying group-by with one field.
func (tdgb *TypeDiseaseGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = tdgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{typedisease.Label}
	default:
		err = fmt.Errorf("ent: TypeDiseaseGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (tdgb *TypeDiseaseGroupBy) StringX(ctx context.Context) string {
	v, err := tdgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by. It is only allowed when querying group-by with one field.
func (tdgb *TypeDiseaseGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(tdgb.fields) > 1 {
		return nil, errors.New("ent: TypeDiseaseGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := tdgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (tdgb *TypeDiseaseGroupBy) IntsX(ctx context.Context) []int {
	v, err := tdgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from group-by. It is only allowed when querying group-by with one field.
func (tdgb *TypeDiseaseGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = tdgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{typedisease.Label}
	default:
		err = fmt.Errorf("ent: TypeDiseaseGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (tdgb *TypeDiseaseGroupBy) IntX(ctx context.Context) int {
	v, err := tdgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by. It is only allowed when querying group-by with one field.
func (tdgb *TypeDiseaseGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(tdgb.fields) > 1 {
		return nil, errors.New("ent: TypeDiseaseGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := tdgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (tdgb *TypeDiseaseGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := tdgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from group-by. It is only allowed when querying group-by with one field.
func (tdgb *TypeDiseaseGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = tdgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{typedisease.Label}
	default:
		err = fmt.Errorf("ent: TypeDiseaseGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (tdgb *TypeDiseaseGroupBy) Float64X(ctx context.Context) float64 {
	v, err := tdgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by. It is only allowed when querying group-by with one field.
func (tdgb *TypeDiseaseGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(tdgb.fields) > 1 {
		return nil, errors.New("ent: TypeDiseaseGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := tdgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (tdgb *TypeDiseaseGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := tdgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from group-by. It is only allowed when querying group-by with one field.
func (tdgb *TypeDiseaseGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = tdgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{typedisease.Label}
	default:
		err = fmt.Errorf("ent: TypeDiseaseGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (tdgb *TypeDiseaseGroupBy) BoolX(ctx context.Context) bool {
	v, err := tdgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (tdgb *TypeDiseaseGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := tdgb.sqlQuery().Query()
	if err := tdgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (tdgb *TypeDiseaseGroupBy) sqlQuery() *sql.Selector {
	selector := tdgb.sql
	columns := make([]string, 0, len(tdgb.fields)+len(tdgb.fns))
	columns = append(columns, tdgb.fields...)
	for _, fn := range tdgb.fns {
		columns = append(columns, fn(selector))
	}
	return selector.Select(columns...).GroupBy(tdgb.fields...)
}

// TypeDiseaseSelect is the builder for select fields of TypeDisease entities.
type TypeDiseaseSelect struct {
	config
	fields []string
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Scan applies the selector query and scan the result into the given value.
func (tds *TypeDiseaseSelect) Scan(ctx context.Context, v interface{}) error {
	query, err := tds.path(ctx)
	if err != nil {
		return err
	}
	tds.sql = query
	return tds.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (tds *TypeDiseaseSelect) ScanX(ctx context.Context, v interface{}) {
	if err := tds.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from selector. It is only allowed when selecting one field.
func (tds *TypeDiseaseSelect) Strings(ctx context.Context) ([]string, error) {
	if len(tds.fields) > 1 {
		return nil, errors.New("ent: TypeDiseaseSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := tds.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (tds *TypeDiseaseSelect) StringsX(ctx context.Context) []string {
	v, err := tds.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from selector. It is only allowed when selecting one field.
func (tds *TypeDiseaseSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = tds.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{typedisease.Label}
	default:
		err = fmt.Errorf("ent: TypeDiseaseSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (tds *TypeDiseaseSelect) StringX(ctx context.Context) string {
	v, err := tds.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from selector. It is only allowed when selecting one field.
func (tds *TypeDiseaseSelect) Ints(ctx context.Context) ([]int, error) {
	if len(tds.fields) > 1 {
		return nil, errors.New("ent: TypeDiseaseSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := tds.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (tds *TypeDiseaseSelect) IntsX(ctx context.Context) []int {
	v, err := tds.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from selector. It is only allowed when selecting one field.
func (tds *TypeDiseaseSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = tds.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{typedisease.Label}
	default:
		err = fmt.Errorf("ent: TypeDiseaseSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (tds *TypeDiseaseSelect) IntX(ctx context.Context) int {
	v, err := tds.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from selector. It is only allowed when selecting one field.
func (tds *TypeDiseaseSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(tds.fields) > 1 {
		return nil, errors.New("ent: TypeDiseaseSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := tds.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (tds *TypeDiseaseSelect) Float64sX(ctx context.Context) []float64 {
	v, err := tds.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from selector. It is only allowed when selecting one field.
func (tds *TypeDiseaseSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = tds.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{typedisease.Label}
	default:
		err = fmt.Errorf("ent: TypeDiseaseSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (tds *TypeDiseaseSelect) Float64X(ctx context.Context) float64 {
	v, err := tds.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from selector. It is only allowed when selecting one field.
func (tds *TypeDiseaseSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(tds.fields) > 1 {
		return nil, errors.New("ent: TypeDiseaseSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := tds.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (tds *TypeDiseaseSelect) BoolsX(ctx context.Context) []bool {
	v, err := tds.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from selector. It is only allowed when selecting one field.
func (tds *TypeDiseaseSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = tds.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{typedisease.Label}
	default:
		err = fmt.Errorf("ent: TypeDiseaseSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (tds *TypeDiseaseSelect) BoolX(ctx context.Context) bool {
	v, err := tds.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (tds *TypeDiseaseSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := tds.sqlQuery().Query()
	if err := tds.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (tds *TypeDiseaseSelect) sqlQuery() sql.Querier {
	selector := tds.sql
	selector.Select(selector.Columns(tds.fields...)...)
	return selector
}
