// Code generated by entc, DO NOT EDIT.

package organ

const (
	// Label holds the string label denoting the organ type in the database.
	Label = "organ"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOrganName holds the string denoting the organname field in the database.
	FieldOrganName = "organ_name"

	// EdgeForogan holds the string denoting the forogan edge name in mutations.
	EdgeForogan = "forogan"

	// Table holds the table name of the organ in the database.
	Table = "organs"
	// ForoganTable is the table the holds the forogan relation/edge.
	ForoganTable = "spacialities"
	// ForoganInverseTable is the table name for the Spaciality entity.
	// It exists in this package in order to avoid circular dependency with the "spaciality" package.
	ForoganInverseTable = "spacialities"
	// ForoganColumn is the table column denoting the forogan relation/edge.
	ForoganColumn = "organ_forogan"
)

// Columns holds all SQL columns for organ fields.
var Columns = []string{
	FieldID,
	FieldOrganName,
}

var (
	// OrganNameValidator is a validator for the "OrganName" field. It is called by the builders before save.
	OrganNameValidator func(string) error
)
