// Code generated by entc, DO NOT EDIT.

package organ

import (
	"github.com/Pichais/app/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Organ {
	return predicate.Organ(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Organ {
	return predicate.Organ(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Organ {
	return predicate.Organ(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Organ {
	return predicate.Organ(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Organ {
	return predicate.Organ(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Organ {
	return predicate.Organ(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Organ {
	return predicate.Organ(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Organ {
	return predicate.Organ(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Organ {
	return predicate.Organ(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// OrganName applies equality check predicate on the "OrganName" field. It's identical to OrganNameEQ.
func OrganName(v string) predicate.Organ {
	return predicate.Organ(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldOrganName), v))
	})
}

// OrganNameEQ applies the EQ predicate on the "OrganName" field.
func OrganNameEQ(v string) predicate.Organ {
	return predicate.Organ(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldOrganName), v))
	})
}

// OrganNameNEQ applies the NEQ predicate on the "OrganName" field.
func OrganNameNEQ(v string) predicate.Organ {
	return predicate.Organ(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldOrganName), v))
	})
}

// OrganNameIn applies the In predicate on the "OrganName" field.
func OrganNameIn(vs ...string) predicate.Organ {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Organ(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldOrganName), v...))
	})
}

// OrganNameNotIn applies the NotIn predicate on the "OrganName" field.
func OrganNameNotIn(vs ...string) predicate.Organ {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Organ(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldOrganName), v...))
	})
}

// OrganNameGT applies the GT predicate on the "OrganName" field.
func OrganNameGT(v string) predicate.Organ {
	return predicate.Organ(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldOrganName), v))
	})
}

// OrganNameGTE applies the GTE predicate on the "OrganName" field.
func OrganNameGTE(v string) predicate.Organ {
	return predicate.Organ(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldOrganName), v))
	})
}

// OrganNameLT applies the LT predicate on the "OrganName" field.
func OrganNameLT(v string) predicate.Organ {
	return predicate.Organ(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldOrganName), v))
	})
}

// OrganNameLTE applies the LTE predicate on the "OrganName" field.
func OrganNameLTE(v string) predicate.Organ {
	return predicate.Organ(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldOrganName), v))
	})
}

// OrganNameContains applies the Contains predicate on the "OrganName" field.
func OrganNameContains(v string) predicate.Organ {
	return predicate.Organ(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldOrganName), v))
	})
}

// OrganNameHasPrefix applies the HasPrefix predicate on the "OrganName" field.
func OrganNameHasPrefix(v string) predicate.Organ {
	return predicate.Organ(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldOrganName), v))
	})
}

// OrganNameHasSuffix applies the HasSuffix predicate on the "OrganName" field.
func OrganNameHasSuffix(v string) predicate.Organ {
	return predicate.Organ(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldOrganName), v))
	})
}

// OrganNameEqualFold applies the EqualFold predicate on the "OrganName" field.
func OrganNameEqualFold(v string) predicate.Organ {
	return predicate.Organ(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldOrganName), v))
	})
}

// OrganNameContainsFold applies the ContainsFold predicate on the "OrganName" field.
func OrganNameContainsFold(v string) predicate.Organ {
	return predicate.Organ(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldOrganName), v))
	})
}

// HasForogan applies the HasEdge predicate on the "forogan" edge.
func HasForogan() predicate.Organ {
	return predicate.Organ(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ForoganTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ForoganTable, ForoganColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasForoganWith applies the HasEdge predicate on the "forogan" edge with a given conditions (other predicates).
func HasForoganWith(preds ...predicate.Spaciality) predicate.Organ {
	return predicate.Organ(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ForoganInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ForoganTable, ForoganColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Organ) predicate.Organ {
	return predicate.Organ(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Organ) predicate.Organ {
	return predicate.Organ(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Organ) predicate.Organ {
	return predicate.Organ(func(s *sql.Selector) {
		p(s.Not())
	})
}
