// Code generated by entc, DO NOT EDIT.

package physician

const (
	// Label holds the string label denoting the physician type in the database.
	Label = "physician"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPhysicianName holds the string denoting the physicianname field in the database.
	FieldPhysicianName = "physician_name"
	// FieldPhysicianEmail holds the string denoting the physicianemail field in the database.
	FieldPhysicianEmail = "physician_email"

	// EdgeForuser holds the string denoting the foruser edge name in mutations.
	EdgeForuser = "foruser"

	// Table holds the table name of the physician in the database.
	Table = "physicians"
	// ForuserTable is the table the holds the foruser relation/edge.
	ForuserTable = "spacialities"
	// ForuserInverseTable is the table name for the Spaciality entity.
	// It exists in this package in order to avoid circular dependency with the "spaciality" package.
	ForuserInverseTable = "spacialities"
	// ForuserColumn is the table column denoting the foruser relation/edge.
	ForuserColumn = "physician_foruser"
)

// Columns holds all SQL columns for physician fields.
var Columns = []string{
	FieldID,
	FieldPhysicianName,
	FieldPhysicianEmail,
}

var (
	// PhysicianNameValidator is a validator for the "PhysicianName" field. It is called by the builders before save.
	PhysicianNameValidator func(string) error
	// PhysicianEmailValidator is a validator for the "PhysicianEmail" field. It is called by the builders before save.
	PhysicianEmailValidator func(string) error
)
