/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntSpaciality,
    EntSpacialityFromJSON,
    EntSpacialityFromJSONTyped,
    EntSpacialityToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntOrganEdges
 */
export interface EntOrganEdges {
    /**
     * Forogan holds the value of the forogan edge.
     * @type {Array<EntSpaciality>}
     * @memberof EntOrganEdges
     */
    forogan?: Array<EntSpaciality>;
}

export function EntOrganEdgesFromJSON(json: any): EntOrganEdges {
    return EntOrganEdgesFromJSONTyped(json, false);
}

export function EntOrganEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntOrganEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'forogan': !exists(json, 'forogan') ? undefined : ((json['forogan'] as Array<any>).map(EntSpacialityFromJSON)),
    };
}

export function EntOrganEdgesToJSON(value?: EntOrganEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'forogan': value.forogan === undefined ? undefined : ((value.forogan as Array<any>).map(EntSpacialityToJSON)),
    };
}


