/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntSpacialityEdges,
    EntSpacialityEdgesFromJSON,
    EntSpacialityEdgesFromJSONTyped,
    EntSpacialityEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntSpaciality
 */
export interface EntSpaciality {
    /**
     * 
     * @type {EntSpacialityEdges}
     * @memberof EntSpaciality
     */
    edges?: EntSpacialityEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntSpaciality
     */
    id?: number;
}

export function EntSpacialityFromJSON(json: any): EntSpaciality {
    return EntSpacialityFromJSONTyped(json, false);
}

export function EntSpacialityFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntSpaciality {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'edges': !exists(json, 'edges') ? undefined : EntSpacialityEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntSpacialityToJSON(value?: EntSpaciality | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'edges': EntSpacialityEdgesToJSON(value.edges),
        'id': value.id,
    };
}


